"""Prometheus metrics for the DICOM receiver."""

from __future__ import annotations

from prometheus_client import Counter, Histogram

INSTANCES_RECEIVED = Counter(
    "dicom_instances_received_total",
    "DICOM instances accepted via C-STORE",
    ["modality"],
)
STORE_FAILURES = Counter(
    "dicom_store_failures_total",
    "C-STORE requests that failed processing",
    ["stage"],
)
PREVIEWS_GENERATED = Counter(
    "dicom_previews_generated_total",
    "PNG previews generated by the preprocessing pipeline",
)
STORE_LATENCY = Histogram(
    "dicom_store_seconds",
    "End-to-end C-STORE handling latency",
)
